/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Vincent
 */
public class Grille extends javax.swing.JPanel {

    /**
     * Creates new form Grille
     */
    public boolean grilleActive;
    
    public Grille() {
        initComponents();
        this.grilleActive = false;
    }
     public void paintGrid(Graphics g)
    {
        if(!this.grilleActive)
        {
            this.grilleActive = true;
            super.paintComponents(g);
            g.setColor(Color.GRAY);
            for (int i = 0; i <= this.getWidth(); i+=10)
            {
                g.drawLine(i, 0, i, this.getHeight());
            }
            for (int i = 0; i <= this.getWidth(); i+=10)
            {
                g.drawLine(0, i, this.getWidth(), i);
            }
        }
        else {
            
            this.grilleActive = false;
            this.repaint();
           
        }
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
